= Обобщённый пример

document_3_xml - это ссылка на соответствующий svg-файл.
Но она не кликабельна, т.к. гитхаб и гитлаб рнедерят даже SVG, видимо, в растровом формате.

Гитхаб не рендерит по умолчанию плантюмл, но у нас гитлаб, мы туда это прикрутили.

Весь сыр-бор в том, что при рендеринге ссылки не кликабельны.

Сначала мы это делали в маркдауне, там рендерится в растре, в png, ссылок, конечно, нет, потом переделал на asciidoc, там можно рендерить в SVG, вроде вот оно, ан нет, гитлаб и SVG рендерит, видимо, как растр.

Елинственный пока вариант - локально открывать диаграмму, экспортнутую из puml в SVG, в браузере. +
Локально браузер нормально отображает кликабельные ссылки в SVG. +
Но это как-то криво... +
И браузер локально не поддерживает ни md, ни asciidoc

Есть ли варианты? Делал ли кто-то подобное?

Сорри, если сумбурно объяснил...

== Диаграмма

[plantuml, format="svg"]
----
@startuml diagram

skinparam defaultTextAlignment center
!pragma useVerticalIf on
scale 1.5

start
floating note right: Procedure DOCUMENT
IF (**if**\n....\ni=1) THEN (yes)
	[[document_3_xml.svg]]#APPLICATION:**document_3_xml**|
ENDIF

stop

@enduml
----
